version: '3.9'

services:
#  client-1:
#    image: 'python:3.12'
#    environment:
#      SERVER_HOST: 'http://server:5000'
#    volumes:
#      - './code/client:/app:ro'
#      - './data/client-1:/app/data:ro'
#    networks:
#      - 'default'

  server:
    build:
      context: '.'
      dockerfile: 'Dockerfile'
    command: ['sleep', 'infinity']
    volumes:
      - './code/server:/app:ro'
    networks:
      - 'default'

#  test:
#    image: tensorflow/tensorflow:latest-gpu
#    command: python -c "import tensorflow as tf;tf.test.gpu_device_name()"
#    deploy:
#      resources:
#        reservations:
#          devices:
#          - driver: nvidia
#            count: 1
#            capabilities: [gpu]

networks:
  default:
    driver: bridge
